### ISSUE TITLE
Importing into Cloud SQL

### ISSUE THREAD

**Issue by lakshmanok** [GoogleCloudPlatform/spark-recommendation-engine#3]
Users can not directly import from your solutions bucket -- they need write permissions (see b/ 27454771).  I've attached a patch to README.md

[fix_gcsperm_patch.zip](https://github.com/GoogleCloudPlatform/spark-recommendation-engine/files/157868/fix_gcsperm_patch.zip)

**Comment by m-mayran** [comment]
I just tried from a personal account and it works as well following these steps:
- click on import
- enter solutions-public-assets/recommendation-spark/sql/table_creation.sql in the input
- choose sql

It should get created and there should be no need of copying the file to your own bucket despite what the b/ says. I will add your comment in case someone runs into the problem though. Thanks
