### ISSUE TITLE
Links to Cloud SQL docs need to be updated

### ISSUE THREAD

**Issue by piaxc** [GoogleCloudPlatform/spark-recommendation-engine#5]
for 
Whitelist the IPs of the nodes as explained in the Cloud SQL documentation.
and
Create an IPv4 address so the Cloud SQL instance

replace 
/sql/docs/access-control#appaccess

with

/sql/docs/external#appaccessIP

**Comment by m-mayran** [comment]
Done. Thank you

**Comment by piaxc** [comment]
Hi, thank you for your quick attention to this. Still need the other link replaced:

Create an IPv4 address so the CLoud SQL instance.

In addition, could you also replace the link here:

Follow these instructions to create

from
/sql/docs/getting-started?hl=en#create

to 

/sql/docs/create-instance

The other doc is going to go away.
Thanks!
