### ISSUE TITLE
Facing Issues

### ISSUE THREAD

**Issue by peterparker123** [GoogleCloudPlatform/spark-recommendation-engine#8]
Hi

While trying to execute the program app_collaborative.py, we have been facing issue. We are executing the program through the command line using gcloud. The following are the command line parameter: 

901C502984LM:pyspark raosa$ gcloud beta dataproc jobs submit pyspark --cluster cluster-1 app_collaborative.py 173.194.229.149 recommendation_spark recommender password 15 20 0.1.

These were the parameters which were given at the console also.

The code errors out with the following message:

Traceback (most recent call last):  
  File "/tmp/07e42a82-714f-4200-bddf-976bbdc467f3/app_collaborative.py", line 83, in <module>
    topPredictions = predictions.takeOrdered(5, key=lambda x: -x[2])

py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: java.lang.StackOverflowError

The configuration of the cluster is:

Name  
cluster-1
Zone  
asia-east1-b
Master node 

Machine type  
n1-highcpu-4 (4 vCPU, 3.60 GB memory)
Primary disk size  
500 GB
Worker nodes  
2
Machine type  
n1-standard-2 (2 vCPU, 7.50 GB memory)
Primary disk size  
500 GB

Could you be able to get this resolved?

Thanks & Regards

**Comment by riteshn-niara** [comment]
I am also seeing the same issue. Has something changed in the data proc environment, causing this?

**Comment by SimonSch** [comment]
Hi, Im also having this same problem. Has anyone managed to find a solution?

**Comment by davidADSP** [comment]
This highlights the problem:
http://stackoverflow.com/questions/31484460/spark-gives-a-stackoverflowerror-when-training-using-als

You need to add checkpointing by including the following two lines in app_collaborative.py

sc.setCheckpointDir('checkpoint/')
ALS.checkpointInterval = 2
